# YouTube Scraper

### Libraries Included

In [4]:
import time
import numpy as np
import pandas as pd
from tqdm import tqdm

from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import chromedriver_binary

In [2]:
df = pd.read_csv('data.csv')

df.head()

,Unnamed: 0,Title,Thumb_img,Vedio_link,No_Views,Duration,No-of-View,TimeStamp
0,0,Get 20LPA+ Jobs with these 5 Unique Project Id...,https://i.ytimg.com/vi/5mw5IzWTFs0/hqdefault.jpg,https://www.youtube.com/watch?v=5mw5IzWTFs0,"1,092",7:04,1092,1900-01-01 00:07:04
1,1,Hate Coding? Upto 44 LPA Non Tech Jobs in 2024...,https://i.ytimg.com/vi/DMhSsL3-SLk/hqdefault.jpg,https://www.youtube.com/watch?v=DMhSsL3-SLk,"1,056",4:22,1056,1900-01-01 00:04:22
2,2,Fun Activity with GFG Students (Worth 20k) ðŸ¥³ðŸ¤‘|...,https://i.ytimg.com/vi/a5C5lCGTIrs/hqdefault.jpg,https://www.youtube.com/watch?v=a5C5lCGTIrs,924,12:32,924,1900-01-01 00:12:32
3,3,Data Analyst vs Data Scientist vs Data Enginee...,https://i.ytimg.com/vi/EHmXVwjtgPs/hqdefault.jpg,https://www.youtube.com/watch?v=EHmXVwjtgPs,"4,583",6:56,4583,1900-01-01 00:06:56
4,4,Top 8 Remote Jobs Websites For Freshers ðŸš€ | E...,https://i.ytimg.com/vi/OIsIZ1w7aTU/hqdefault.jpg,https://www.youtube.com/watch?v=OIsIZ1w7aTU,"2,354",9:22,2354,1900-01-01 00:09:22

In [ ]:
browser=webdriver.Chrome(service=Service(ChromeDriverManager().install()))
browser.get('https://www.youtube.com')
time.sleep(2)

data = []

for link in tqdm(df['Vedio_link']):
    browser.get(link)
    
    time.sleep(5)
    
    soup = BeautifulSoup(browser.page_source, 'html.parser')

    try:
        title = soup.find_all('yt-formatted-string', class_ = 'style-scope ytd-video-primary-info-renderer')[0].text
    except:
        title = np.nan
    
    try:
        view = soup.find('span' , class_ = 'view-count style-scope ytd-video-view-count-renderer').text
    except:
        view = np.nan
        
    try:
        date_time = soup.find_all('yt-formatted-string', class_ = 'style-scope ytd-video-primary-info-renderer')[1].text
    except:
        date_time = np.nan
    
    try:
        like = soup.find('yt-formatted-string', class_ = 'style-scope ytd-toggle-button-renderer style-text').text
    except:
        like = np.nan
      
    try:
        description = soup.find('yt-formatted-string', class_ = 'content style-scope ytd-video-secondary-info-renderer').text
    except:
        description = np.nan
        
    data.append([title , date_time, like, view, link, description])

  0%|   | 7/1818 [00:54<3:59:46,  7.94s/it]

In [18]:
len(data)

2105

In [19]:
df = pd.DataFrame(data, columns = ['title' , 'date_time', 'likes', 'views', 'link' , 'description'])

In [20]:
df.isnull().sum()

title           0
date_time      20
likes           0
views          20
link            0
description     0
dtype: int64

In [21]:
df.to_csv('GFG.csv', index = False)

In [22]:
df

,title,date_time,likes,views,link,description
0,Interview Experience @ Amazon | GeeksforGeeks,Premiered on 6 May 2022,113,"2,521 views",https://www.youtube.com/watch?v=SMgm_gpJyNU,Our courses : \nhttps://practice.geeksforgeeks...
1,Live Mock DSA,Streamed live on 4 May 2022,95,"2,411 views",https://www.youtube.com/watch?v=mwqKJz7K03k,Watch this mock interview to evaluate your str...
2,Interview Experience at Google | Tech Dose,Streamed live on 2 May 2022,264,"5,633 views",https://www.youtube.com/watch?v=V23iPYIQCvc,Do you wish to be a #Noogler?\r\nWe have just ...
3,Life Is Unfair Ft. Shonty badmash | LIVE Disco...,Premiered on 26 Apr 2022,42,"1,623 views",https://www.youtube.com/watch?v=49MRLvZaG3s,Witness our first Discord Live full of fun and...
4,Journey from JIIT to Adobe,26 Apr 2022,38,"1,089 views",https://www.youtube.com/watch?v=9CswKbEqj5A,"In this session, Priya will share her experien..."
...,...,...,...,...,...,...
2100,Length of shortest chain to reach a target wor...,1 Apr 2016,137,"37,819 views",https://www.youtube.com/watch?v=6pIC20wCm20,Explanation for the article: http://www.geeksf...
2101,Binary Search | GeeksQuiz,28 Mar 2016,765,"182,828 views",https://www.youtube.com/watch?v=T2sFYY-fT5o,Explanation for the article: http://geeksquiz....
2102,Number of Triangles in an Undirected Graph | G...,7 Mar 2016,57,"16,470 views",https://www.youtube.com/watch?v=ChdNz1Ui1uc,Explanation for the article: http://www.geeksf...
2103,Write a program to print all permutations of a...,7 Jan 2016,1.8K,"449,925 views",https://www.youtube.com/watch?v=AfxHGNRtFac,Explanation for the Article: http://www.geeksf...
2104,Longest Span with same Sum in two Binary array...,29 Dec 2015,1.1K,"241,456 views",https://www.youtube.com/watch?v=xtfj4-r_Ahs,Here's you next clue - Our comprehensive guid...